### ISSUE TITLE
Can't view properly whitespace or indendation guides in any of the dark themes except solarized(Dark)

### ISSUE THREAD

**Issue by fightthepower** [geany/geany-themes#23]
As the title says; can't view properly whitespace( view-> show whitespace) or indendation guides (view-> show indendtion guides) in none of the dark themes except solarized(Dark).  The only way to see those is by selecting the codes.

**Comment by elextr** [comment]
The indentation guide style is settable in the colour scheme.  Its called "indent_guide" :)

You need to talk to the theme authors it seems.

**Comment by fightthepower** [comment]
Other than the elextr's method, "white_space" is another settable value in colour scheme for viewing indent space.
