### ISSUE TITLE
bold keywords, types, and classes

### ISSUE THREAD

**Issue by nkralpy** [geany/geany-themes#24]
geany's default colour-scheme has boldface for keywords, types, and classes. It would be nice to see the other colour-schemes to follow this. For example, monokai would change as below.

type=bright_green;;true
class=type
function=bright_green
parameter=bright_orange;

keyword=hot_pink;;true
keyword_1=keyword
keyword_2=light_cyan;;true
keyword_3=keyword_1
keyword_4=keyword_2

**Comment by codebrainz** [comment]
This is a choice the individual theme authors make.

**Comment by elextr** [comment]
To expand what @codebrainz said, themes are a matter of personal taste, authors choose combinations of bold and italic and colour that suit their tastes and use-case and fonts (not all fonts have a bold for eg).

The `geany-themes` repo simply collates themes so they can be found in one place, it certainly won't try to impose aspects of personal taste.
