### ISSUE TITLE
Schemes don't show up

### ISSUE THREAD

**Issue by liborty** [geany/geany-themes#28]
.conf files don't show up in the menu

**Comment by liborty** [comment]
.conf files added to .config/geany/colorschemes do not show up in the view-change colorscheme menu at all, even after restart. Only the default and alternate schemes show as before.

**Comment by codebrainz** [comment]
What is the full absolute path to the directory in which you're putting the colour scheme .conf files?

**Comment by liborty** [comment]
I was putting them in the above path in my home directory. Thanks to your hint I have discovered that there is also /usr/local/share/geany/colorschemes. Copied them over but still no effect.

**Comment by liborty** [comment]
Some progs also use .local/share in my $HOME, which is getting quite bizarre but geany is not in there.

**Comment by codebrainz** [comment]
If you're not specifying a `-c` option when launching Geany, it should indeed be `$HOME/.config/geany/colorschemes`. Can you please paste the debug output from `Help->Debug Messages` here?

**Comment by liborty** [comment]
I have now reinstalled geany from default ubuntu mint repositories, as maybe I had some screwed up installation. It is a pity that you don't provide linux binaries or ppa. The schemes now come up in the meny but say (null) and don't show any colours.

Debug Messages:
12:09:58: Geany INFO		: Geany 1.32, en_US.UTF-8
12:09:58: Geany INFO		: GTK 3.22.30, GLib 2.56.3
12:09:58: Geany INFO		: System data dir: /usr/share/geany
12:09:58: Geany INFO		: User config dir: /home/l/.config/geany
12:09:58: Geany INFO		: System plugin path: /usr/lib/i386-linux-gnu/geany
12:09:58: Geany INFO		: Added filetype Arduino (61).
12:09:58: Geany INFO		: Added filetype Genie (62).
12:09:58: Geany INFO		: Added filetype Clojure (63).
12:09:58: Geany INFO		: Added filetype Scala (64).
12:09:58: Geany INFO		: Added filetype CUDA (65).
12:09:58: Geany INFO		: Added filetype Graphviz (66).
12:09:58: Geany INFO		: Added filetype Cython (67).
12:09:58: Geany INFO		: Added filetype JSON (68).
12:09:58: Geany INFO		: Loaded libvte from libvte-2.91.so.0

**Comment by codebrainz** [comment]
Not sure what's going on, maybe make sure `/usr/share/geany/colourschemes` doesn't have these colour schemes in it.

> It is a pity that you don't provide linux binaries or ppa.

The Debian/Ubuntu package maintainer maintains a [PPA here](https://launchpad.net/~geany-dev/+archive/ubuntu/ppa) that provides binaries/packages.

**Comment by liborty** [comment]
Thanks for your help. I have now reinstalled from the PPA and installed all the colour schemes and it finally works! Still not sure if the problem was ubuntu old version or that I previously installed only some of the .conf files.
