### ISSUE TITLE
Themes only applies to editor window

### ISSUE THREAD

**Issue by lcocea** [geany/geany-themes#37]
On Windows 10, these themes seem to apply to the main editor window only. As the rest of the IDE is not Windows-10 theme-compatible, the contrast between the dark editor window and the otherwise bright parts of the IDE makes using dark themes difficult in Geany.

**Comment by elextr** [comment]
These themes are only intended to apply to the editor window, they map syntactic entities of programming languages to styles.

They do not map GUI elements to styles, that is the job of the GTK style which has nothing to do with these styles and this repository, see the main Geany documentation.
