### ISSUE TITLE
all themes negative/reversed colors

### ISSUE THREAD

**Issue by tonybaldwin** [geany/geany-themes#4]
I just grabbed all of these and installed them, and they show reversed/negative. To explain, the Retro (terminal) theme, which should be green on black, is pink on white; Fluffy, which should be white with colors, is instead black. Dark themes are light, and light themes are dark.
It's weird. Any explanation?
At the moment I'm on a crappy win7 machine. (I'll install and look on my Debian box later).

Tony

**Comment by codebrainz** [comment]
You probably have selected "Invert syntax highlighting colors" under Edit->Preferences->Editor->Display section of the preferences.

**Comment by tonybaldwin** [comment]
That was exactly it!
I wonder when I did that....

thanks!
./t

**Comment by codebrainz** [comment]
My guess is after your eyes got tired and you wanted dark theme :)
