### ISSUE TITLE
Missing undescores with Delt Dark theme.

### ISSUE THREAD

**Issue by ogzs** [geany/geany-themes#48]
Hello,

I'm using geany on Ubuntu. Defaults settings except the theme. The text font is "Monospace" size 10.
The undescore characters are not visible (they look like spaces).
I tested with other fonts, some have the same issue, some do not.

Is there some parameter to change somewhere? Some line height ?

**Comment by ogzs** [comment]
Sorry, it's probably not related to the theme : I've got the same issue with the default theme.

**Comment by elextr** [comment]
See https://github.com/geany/geany/issues/2466
