### ISSUE TITLE
Alternate line background color?

### ISSUE THREAD

**Issue by paul1149** [geany/geany-themes#51]
Is it possible to write in an second background color for alternate lines? This would be very attractive to the eye. I didn't see theme specs anywhere. Thanks.

**Comment by elextr** [comment]
No.

The background colour is part of the styles set for the syntactic elements by the filetype specific lexers.  This would imply that the lexical elements would need differing styles for alternate lines and that the lexer would have to use different ones on alternate lines.

The lexers come from the [Lexilla](https://github.com/ScintillaOrg/lexilla) project.  You could ask there.

**Comment by paul1149** [comment]
Ok, thanks much. I have asked over there.
