### ISSUE TITLE
How to change colorscheme?

### ISSUE THREAD

**Issue by RichardJECooke** [geany/geany-themes#6]
I followed the instructions on the homepage exactly, but my colorscheme hasn't changed when I restart Geany. Are there missing instructions?

"Extract the tarball and copy all of the files in the colorschemes directory to your C:\Users\YourUserName\AppData\Roaming\geany\colorschemes directory. Create this directory if it doesn't already exist."

**Comment by elextr** [comment]
You need to select a new scheme, installing them makes them available, but Geany cannot (yet) read your mind to select which one you want.

**Comment by RichardJECooke** [comment]
Are there instructions on your project homepage I'm not seeing? I can't see anywhere how to select a scheme.  There doesn't appear to be a setting in Preferences - Interface. Is it something I need to do to the files manually in my OS?

**Comment by elextr** [comment]
Menu->View->Change Colour Scheme...

See [here](http://www.geany.org/manual/current/index.html#view-menu)

**Comment by RichardJECooke** [comment]
Ohhhh, thanks. 
(I think it could help a lot of people if you added this one line to your readme file.)

**Comment by stehgold** [comment]
There's only Default and Alternate to choose from. 

What is it with the version numbers ? My Geany says it's 1.26

**Comment by janjackson** [comment]
I also struggled to figure out that you have to move them up in the directory. Could you add this to the readme for Ubuntu installation?1) unwrap and move tarball

**Comment by elextr** [comment]
@janjackson the README already says:

```
Extract the tarball and copy all of the files in the colorschemes directory to your ~/.config/geany/colorschemes/ directory. Create that directory if it doesn't already exist.
```

And choosing the colour scheme is already in the Geany manual as I linked in my previous post.

**Comment by codebrainz** [comment]
@janjackson I updated the README file in 4598c9f3b06d1464e58f693a38b97e32ee73babf, hopefully it's a little more clear now.

**Comment by gabrielnemeth** [comment]
I installed Geany 1.37.1 flatpack on pop_os. I copied first manually, then using the `install.sh` the config files. I restarted Geany and my system too, but I see only default and alternate themes in the color schemes popup.

**Comment by elextr** [comment]
@gabrielnemeth thats a problem with flatpacks.  The Geany project does not make the flatpack, you should raise the problem with your OS.
