### ISSUE TITLE
A few broken colour schemes that come with Geany 2.0 (comma instead of semicolon on brace_good line)

### ISSUE THREAD

**Issue by that-ben** [geany/geany-themes#65]
Geany 2.0 comes with a few broken colour scheme templates. Look at the brace_good line in the following screenshot, you will see a typo where there's a comma instead of a semicolon:

<img width="1488" alt="282243403-bd321a08-adc3-461b-807a-145057b4bb9e" src="https://github.com/geany/geany-themes/assets/13210399/9ee385b4-8a8a-4e6f-b5d8-887abacad513">

When I fix that line, it works properly and braces are highlighted, otherwise (by default) they're black on dark gray, so the highlighting is almost completely unnoticeable.

Please fix your schemes, the line should be reading:

brace_good=pro_orange;pro_selection_background;true;false

Make sure to also check the light scheme from the same name as it contains the same typo! ;-)

Issue initially raised over at Geany 2.0 GitHub: https://github.com/geany/geany-osx/issues/50#issuecomment-1806816745

**Comment by techee** [comment]
Fixed, thanks for reporting.
