### ISSUE TITLE
Relicensing the epsilon theme under GPL 2 or later

### ISSUE THREAD

**Issue by techee** [geany/geany-themes#79]
We would like to include all the themes from geany-themes in the geany release tarball and distribute them with Geany itself. Geany is licensed under "GPL 2 or later" and to be on the safe side, we will probably only use themes that are compatible with Geany's license (see the discussion in [#4044](https://github.com/geany/geany/pull/4044)).

@N3mesis98 The epsilon theme you created for Geany is currently licensed as "GPL 3 or later" which isn't compatible with Geany's "GPL 2 or later". Would it be possible to relicense it under "GPL 2 or later"?

**Comment by N3mesis98** [comment]
Hello,
Yes, it is fine to make it GPL 2 or later.

**Comment by techee** [comment]
@N3mesis98 Thanks! Does #81 look good to you? (I used the same GPL wording like in other GPL 2 licenses so there are some minor modifications in addition to the number)

**Comment by N3mesis98** [comment]
Yes, I reviewed the correponding commit and agree with the changes.

**Comment by rdipardo** [comment]
> "GPL 3 or later" which isn't compatible with Geany's "GPL 2 or later"

Source? I thought is was "GPL 2 __*only*__" that was incompatible, whereas

> if code is released under GPL "version 2 or later," that is compatible with GPLv3 because GPLv3 is one of the options it permits.
>
> <https://www.gnu.org/licenses/gpl-faq.html#v2v3Compatibility>

**Comment by techee** [comment]
> Source? I thought is was "GPL 2 only" that was incompatible, whereas

> if code is released under GPL "version 2 or later," that is compatible with GPLv3 because GPLv3 is one of the options it permits.

I meant the compatibility in terms of "Geany as a whole, including all stuff in it, is licensed under GPLv2 or later" which wouldn't be possible if the theme were GPLv3 or later. Check the matrix at the bottom of the FAQ or the picture in https://en.wikipedia.org/wiki/License_compatibility#Compatibility_of_FOSS_licenses
