### ISSUE TITLE
License of the tango-dark theme

### ISSUE THREAD

**Issue by techee** [geany/geany-themes#80]
We would like to include all the themes from geany-themes in the geany release tarball and distribute them with Geany itself. Geany is licensed under "GPL 2 or later" and to be on the safe side, we will probably only use themes that are compatible with Geany's license (see the discussion in https://github.com/geany/geany/pull/4044).

@barryvan What is the license of the tango-dark theme? There's no explicit license in the theme at the moment. Ideally for us, it should be something compatible with Geany's "GPL 2 or later", that is one of the following:
- public domain
- MIT
- BSD
- LGPL 2.1 or later
- GPL 2 or later

**Comment by barryvan** [comment]
I don't think I ever specifically licensed it, so let's go with Public Domain. 😊

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: Jiří Techet ***@***.***>
Sent: Saturday, December 28, 2024 1:07:24 AM
To: geany/geany-themes ***@***.***>
Cc: Barry van Oudtshoorn ***@***.***>; Mention ***@***.***>
Subject: [geany/geany-themes] License of the tango-dark theme (Issue #80)


We would like to include all the themes from geany-themes in the geany release tarball and distribute them with Geany itself. Geany is licensed under "GPL 2 or later" and to be on the safe side, we will probably only use themes that are compatible with Geany's license (see the discussion in geany/geany#4044<https://github.com/geany/geany/pull/4044>).

@barryvan<https://github.com/barryvan> What is the license of the tango-dark theme? There's no explicit license in the theme at the moment. Ideally for us, it should be something compatible with Geany's "GPL 2 or later", that is one of the following:

  *   public domain
  *   MIT
  *   BSD
  *   LGPL 2.1 or later
  *   GPL 2 or later

**Comment by techee** [comment]
Fixed by #82.
